---
- include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ landscape_version }}.yml'
        - main.yml
      paths:
        - 'vars'

- include_tasks: check.yml
  tags: check

- include_tasks: prepare.yml
  tags: prepare

- include_tasks: install.yml
  tags: install
