---
- name: Converge
  hosts: landscape-server-2303
  roles:
    - role: server
      server_version: '23.03'

- name: Converge
  hosts: landscape-server-2310
  roles:
    - role: server
      server_version: '23.10'
