---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: landscape-server-2404
    image: docker.io/ubuntu:24.04
    published_ports:
      - 127.0.0.1:8080:80
      - 127.0.0.1:8443:443
provisioner:
  name: ansible
verifier:
  name: testinfra
lint: |
  yamllint .
  ansible-lint
  flake8
