---
storage_vg: vg_landscape
storage_pv: /dev/sdb
storage_packages:
  - xfsprogs
  - lvm2
server_filesystems:
  - name: lv_pgsql
    type: xfs
    mountpoint: /var/lib/postgresql
    size: 5120
  - name: lv_landscape
    type: xfs
    mountpoint: /var/lib/landscape
    size: 20480
